name: Update Streamlit App Productive

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 17 * * 2,5' # Runs every Tuesday and Friday at 5 PM UTC
      timezone: 'Europe/London'  # Specify the British timezone

jobs:
  update-streamlit-app:
    runs-on: windows-latest # Adjust the runner based on your requirements

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Install Python Dependencies
      run: |
        # Install packages from requirements.update.txt
        pip install -r requirements.update.txt

    - name: Run Batch Script
      working-directory: .\
      run: |
        # Run the batch script to update the Streamlit app
        .\scripts\batch_runs\workflow_update_streamlit_app.bat

    - name: Configure Git
      run: |
        # Configure Git with user information
        git config --global user.name "Robert Gerth"
        git config --global user.email "robert.gerth@mail.de"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update Streamlit App"
        body: "This pull request updates the Streamlit app."
        branch: update-streamlit-app # Replace with your branch name
        base: main # The branch you want to merge into (main)

    - name: Complete Workflow
      run: |
        # Print a message indicating the workflow is complete
        echo "Workflow completed."

